### ISSUE TITLE
competition update After seconds.

### ISSUE THREAD

**Issue by aliciawangeci** [sotetalent/sotetalent#2]
![screenshot from 2018-04-10 13-10-58](https://user-images.githubusercontent.com/32129381/38551084-f8525a46-3cc0-11e8-8312-8eb806448811.png)

That's the terminal after starting the app. I don't understand why you have to keep the connection updating after a number of seconds from the api url. Maybe you should keep the connection updating after a longer time. Like say 60 seconds. 

Please explain your decision.

**Comment by mwamodojnr** [comment]
This is because there is a limit to the number of applications being taken for each competition at any particular time. If the API is not updating the page then an applicant may start the process only to find all the spots are taken. Thus the need for AJAX.
But since we are not expecting large number of application at the same time we can increase the pings.
This was only meant to be really scalable.
